apiVersion: v1
kind: Service
metadata:
  name: falco
  namespace: falco
spec:
  selector:
    app.kubernetes.io/name: falco
  ports:
    - name: grpc
      protocol: TCP
      port: 5060
      targetPort: 5060
  clusterIP: None
